### ISSUE TITLE
vuepress@2.0.0-rc.14   no such file or directory, open '.....\node_modules\@vuepress\theme-default\lib\client\components\Page.vue'

### ISSUE THREAD

**Issue by Nuyoah0525** [dingshaohua-cn/vuepress-theme-sidebar#12]
Error: ENOENT: no such file or directory, open 'D:\school\yh-blog\node_modules\@vuepress\theme-default\lib\client\components\Page.vue'
    at Object.readFileUtf8 (node:internal/fs/sync:25:18)
    at Object.readFileSync (node:fs:441:19)
    at file:///D:/school/yh-blog/node_modules/vuepress-theme-sidebar/index.js:10:26
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadUserConfig (file:///D:/school/yh-blog/node_modules/@vuepress/cli/dist/index.js:77:18)
    at async CAC.dev (file:///D:/school/yh-blog/node_modules/@vuepress/cli/dist/index.js:443:52)
error Command failed with exit code 1.

**Comment by Nuyoah0525** [comment]
使用yarn 管理

**Comment by rmray** [comment]
同样的问题，不知道怎么回事！

**Comment by LBC000** [comment]
同样的问题，不知道怎么回事！pnpm 安装的

**Comment by kgloveyou** [comment]
npm，同样的问题，有人解决了吗

**Comment by XY0797** [comment]
最新版本的vuepress大改了页面加载模式，导致本插件不再适配
本插件需要重写才能适配

**Comment by XY0797** [comment]
我用的旧版本是可正常用，如果非用不可可以降级，或者换vitepress
```
  "devDependencies": {
    "@vuepress/bundler-vite": "^2.0.0-rc.2",
    "@vuepress/theme-default": "^2.0.0-rc.9",
    "vuepress": "^2.0.0-rc.2"
  },
  "dependencies": {
    "vuepress-theme-sidebar": "^0.1.0"
  }
```
